---
.travis.yml:
  secure: "EnDnwMWmc74k0xh58p4Lhlp/MGSGScmKQmqWYXLsXaX52hvX2hv4z9lvbUp0xzilcHxqJW8Yhg2c1Fyk9WxVOnQ0vyxChLf4qeLeW8LebU2J91LgWqcckfmF907RXdNtrijJ2786r4dmO834BEklFoyKP0/2LP6N27lbZHX+0NBPl80O7x8/XHFhvQC6b03BVQjsFbHKU38xJQsP8NZhG5Zk1YFocHl4YWx9yNN+uZqivwk+gO68OqujQyvmqlSGlhEcuUS5qztzC0FpcHXjBcAnVAzBYwluAWfEctu04uxOu98500vGLokNCNLFsxG5TwTvQjBiLfyS6i+nnPCghUzbDyaNiywuCOWS3guDpLH0u6tqS8Uxb2Hv9zc68LovUK+v/UDXd+IRJl1OqL0LzC7VDTfLHax8l4Wa5ZQ7CiMoN+1zj66aI7eJxRBHNPt4WOYK3CeDZ4TeGpQX/VZEpCtG+DqgjJ7A2wMS8kfl+3ptZ0UatgIkWqrBA40+vxg1g6h8tbfTHWknmtOvV/cunG/3QH46QtLhIGIewxcBAG3VIfoSTyJXWQcNIHumIA/votzL4o9FZNFlTphtHPUJZNRoLbd5pMRmmXjdkY9GZx+SbjvuakCFUI5tAM51rk5hjNRJMZQScQQi9boIKi3hbHSK2zLLXDLzlhHVNTX9z+k="
  docker_sets:
    - set: centos7-64
spec/spec_helper_acceptance.rb:
  unmanaged: false
spec/acceptance/nodesets/archlinux-2-x64.yml:
  delete: true
